# Generated by Django 2.2.12 on 2024-04-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('block_width', models.IntegerField()),
                ('block_height', models.IntegerField()),
                ('vector', models.TextField()),
            ],
            options={
                'db_table': 'faces',
            },
        ),
    ]
